const ADMIN_PASSWORD="123456";if(localStorage.getItem('adminLogged')==='yes'){document.getElementById('loginSection').style.display='none';document.getElementById('adminPanel').style.display='block';showAdminTab('products');}
window.checkPassword=function(){if(document.getElementById('adminPassword').value===ADMIN_PASSWORD){localStorage.setItem('adminLogged','yes');document.getElementById('loginSection').style.display='none';document.getElementById('adminPanel').style.display='block';showToast('✅ تم التسجيل');showAdminTab('products');}else{showToast('❌ خطأ');}};
window.logout=function(){localStorage.removeItem('adminLogged');location.reload();};
function showToast(m){let t=document.getElementById('toast');if(!t)return;t.textContent=m;t.style.display='block';t.style.backgroundColor=m.includes('✅')?'#4CAF50':'#f44336';setTimeout(()=>t.style.display='none',3000);}
function isAdmin(){return localStorage.getItem('adminLogged')==='yes';}
function loadStoreData(){let d=localStorage.getItem('storeData');if(d)return JSON.parse(d);return{sections:[{name:"الألعاب",categories:[{name:"PUBG",products:[{name:"شدات PUBG 1000 UC",price:10},{name:"شدات PUBG 2000 UC",price:18}]},{name:"Free Fire",products:[{name:"شدات Free Fire 500",price:8},{name:"شدات Free Fire 1000",price:15}]}]},{name:"التطبيقات",categories:[{name:"Google Play",products:[{name:"بطاقة Google Play 10$",price:12},{name:"بطاقة Google Play 20$",price:22}]}]}]};}
function saveStoreData(d){localStorage.setItem('storeData',JSON.stringify(d));}
let storeData=loadStoreData();
window.showAdminTab=function(t){document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.admin-tab-content').forEach(c=>c.classList.remove('active'));document.querySelectorAll('.tab-btn').forEach(b=>{if(b.textContent.includes(t==='products'?'المنتجات':t==='orders'?'الطلبات':t==='users'?'العملاء':'الإحصائيات'))b.classList.add('active');});document.getElementById('admin'+t.charAt(0).toUpperCase()+t.slice(1)).classList.add('active');if(t==='products')loadAdminProducts();if(t==='orders')loadAdminOrders();if(t==='users')loadAdminUsers();if(t==='stats')loadAdminStats();};
function loadAdminProducts(){let h='<h3>📦 إدارة المنتجات</h3>';storeData.sections.forEach((s,i)=>{s.categories.forEach((c,j)=>{h+=`<div style="margin-bottom:20px"><h4 style="color:#fbbf24">${c.name}</h4>`;c.products.forEach((p,k)=>{h+=`<div class="product-edit-card"><div class="product-edit-row"><input type="text" id="name_${i}_${j}_${k}" value="${p.name}"><input type="number" id="price_${i}_${j}_${k}" value="${p.price}" step="0.01"></div><div class="product-edit-actions"><button class="save-btn" onclick="updateProduct(${i},${j},${k})">💾 حفظ</button><button class="delete-btn" onclick="deleteProduct(${i},${j},${k})">🗑️ حذف</button></div></div>`;});h+=`<div style="margin-top:10px"><input type="text" id="new_name_${i}_${j}" placeholder="اسم منتج جديد" style="width:100%;background:#333;border:1px solid #fbbf24;border-radius:10px;padding:12px;margin-bottom:10px;color:#fff"><input type="number" id="new_price_${i}_${j}" placeholder="السعر" step="0.01" style="width:100%;background:#333;border:1px solid #fbbf24;border-radius:10px;padding:12px;margin-bottom:10px;color:#fff"><button class="add-btn" onclick="addProduct(${i},${j})">➕ إضافة</button></div></div>`;});});document.getElementById('adminProducts').innerHTML=h;}
window.updateProduct=function(s,c,p){let n=document.getElementById(`name_${s}_${c}_${p}`).value;let pr=parseFloat(document.getElementById(`price_${s}_${c}_${p}`).value);if(!n||isNaN(pr))return showToast('❌ بيانات');storeData.sections[s].categories[c].products[p]={name:n,price:pr};saveStoreData(storeData);showToast('✅ تم');loadAdminProducts();};
window.deleteProduct=function(s,c,p){if(!confirm('حذف؟'))return;storeData.sections[s].categories[c].products.splice(p,1);saveStoreData(storeData);loadAdminProducts();showToast('✅ حذف');};
window.addProduct=function(s,c){let n=document.getElementById(`new_name_${s}_${c}`).value;let pr=parseFloat(document.getElementById(`new_price_${s}_${c}`).value);if(!n||isNaN(pr))return showToast('❌ بيانات');storeData.sections[s].categories[c].products.push({name:n,price:pr});saveStoreData(storeData);document.getElementById(`new_name_${s}_${c}`).value='';document.getElementById(`new_price_${s}_${c}`).value='';loadAdminProducts();showToast('✅ إضافة');};
function loadAdminOrders(){if(!isAdmin())return;let o=JSON.parse(localStorage.getItem('orders'))||[];let h='<h3>📋 الطلبات</h3>';if(o.length===0)h+='<p style="text-align:center">لا توجد</p>';else{o.sort((a,b)=>new Date(b.date)-new Date(a.date));o.forEach((od,i)=>{h+=`<div style="background:#1a1a1a;border-radius:10px;padding:15px;margin-bottom:10px"><div><strong>${od.product}</strong> - ${od.price}$</div><div style="font-size:12px">المستخدم: ${od.userEmail||'غير معروف'}</div><div style="font-size:12px">معرف: ${od.playerId||'غير محدد'}</div><div style="font-size:10px;color:#666">${new Date(od.date).toLocaleString()}</div><select id="order_${i}" style="width:100%;margin:10px 0;padding:8px;background:#333;color:#fff;border:1px solid #fbbf24;border-radius:5px"><option value="pending" ${od.status==='pending'?'selected':''}>⏳ قيد</option><option value="completed" ${od.status==='completed'?'selected':''}>✅ مكتمل</option></select><button onclick="updateOrderStatus(${i})" style="width:100%;background:#fbbf24;color:#000;border:none;padding:8px;border-radius:5px;font-weight:700">تحديث</button></div>`;});}document.getElementById('adminOrders').innerHTML=h;}
window.updateOrderStatus=function(i){let o=JSON.parse(localStorage.getItem('orders'))||[];let s=document.getElementById(`order_${i}`);if(!s)return;o[i].status=s.value;localStorage.setItem('orders',JSON.stringify(o));showToast('✅ تم');loadAdminOrders();};
function loadAdminUsers(){if(!isAdmin())return;let u=JSON.parse(localStorage.getItem('users'))||[];let h='<h3>👥 العملاء</h3><table style="width:100%;border-collapse:collapse"><tr><th>الاسم</th><th>البريد</th><th>الرصيد</th><th>التسجيل</th></tr>';if(u.length===0)h+='<tr><td colspan="4" style="text-align:center">لا يوجد</td></tr>';else{u.forEach(us=>{h+=`<tr><td style="padding:8px;border-bottom:1px solid #333">${us.name||'غير معروف'}</td><td style="padding:8px;border-bottom:1px solid #333">${us.email||'—'}</td><td style="padding:8px;border-bottom:1px solid #333;color:#fbbf24">${us.walletBalance||0}$</td><td style="padding:8px;border-bottom:1px solid #333;font-size:10px">${us.createdAt?new Date(us.createdAt).toLocaleDateString():'-'}</td></tr>`;});}h+='</table>';document.getElementById('adminUsers').innerHTML=h;}
function loadAdminStats(){if(!isAdmin())return;let u=JSON.parse(localStorage.getItem('users'))||[];let o=JSON.parse(localStorage.getItem('orders'))||[];let tot=o.length;let sales=o.reduce((s,od)=>s+(od.price||0),0);let pend=o.filter(od=>od.status==='pending').length;document.getElementById('adminStats').innerHTML=`<h3>📊 الإحصائيات</h3><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:10px"><div style="background:#1a1a1a;border-radius:15px;padding:20px;text-align:center"><div style="font-size:32px;color:#fbbf24">${u.length}</div><div>العملاء</div></div><div style="background:#1a1a1a;border-radius:15px;padding:20px;text-align:center"><div style="font-size:32px;color:#fbbf24">${tot}</div><div>الطلبات</div></div><div style="background:#1a1a1a;border-radius:15px;padding:20px;text-align:center"><div style="font-size:32px;color:#fbbf24">${pend}</div><div>قيد الانتظار</div></div><div style="background:#1a1a1a;border-radius:15px;padding:20px;text-align:center"><div style="font-size:32px;color:#fbbf24">${sales}$</div><div>المبيعات</div></div></div>`;